# Generated by Django 6.0 on 2026-02-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='chave_acesso',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cofins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='icms',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ipi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
